### ISSUE TITLE
esiste codice lstlisting per faust?

### ISSUE THREAD

**Issue by grammaton** [s-e-a-m/seam-smc2020#4]
bo

**Comment by DavideTedesco** [comment]
non so se avessi visto questo, ma credo di si https://github.com/grame-cncm/faust/blob/master-dev/documentation/faust-quick-reference-src/chapters/installation.tex

**Comment by grammaton** [comment]
Si… è lo stesso che seguiamo noi, ma con mac dobbiamo aggiungere dei passaggi precedenti il make. 

In ogni caso io non aspetto che pubblichino release e aggiorno più o meno quotidianamente faust e ricompilo.

Utilizzo `make all` in luogo del semplice make… perché produce anche supporti accessori, ma se non smanetti è una cosa che puoi evitare.

G

**Comment by grammaton** [comment]
trovato… preso dal mathdoc export
